config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :contacts  
  resources :posts 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/home'

  resources :handies
  resources :eflashssds
  devise_for :users

resources :handies do
  	collection { post :import , :report}
end

resources :eflashssds do
    collection { post :import }
end

  root to: 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/handy.rb
class Handy < ApplicationRecord
belongs_to :user , optional: true

has_attached_file :image, 
  styles: 
  {   large: "1500x1500", 
      medium: "300x300",
      thumb: "380x380"}, 
      default_url:  ""# "/images/:style/missing.png"

has_attached_file  :image1,
  styles: 
  {   large: "1500x1500", 
      medium: "300x300",
      thumb: "380x380"}, 
      default_url: ""# "/images/:style/missing.png"

      has_attached_file :image2,
  styles: 
  {   large: "1500x1500", 
      medium: "300x300",
      thumb: "380x380"}, 
      default_url: ""# "/images/:style/missing.png"

      has_attached_file :image3, 
  styles: 
  {   large: "1500x1500", 
      medium: "400x400",
      thumb: "380x380"}, 
      default_url: ""# "/images/:style/missing.png"

  #This validates the type of file uploaded. According to this, only images are allowed.
  # validates_attachment_content_type :image, :image1, :image2, :image3,   content_type: /\Aimage\/.*\z/

  #Use this if you do not want to validate the uploaded file type.
     #do_not_validate_attachment_file_type :image

 #Validates file, file type and file size
   validates_attachment :image, :image1, :image2, :image3,  
   content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] },
   size: { in: 0..10000.kilobytes }


	def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Handy.create! row.to_hash
    end
  end

def self.to_csv(options = {})
  # if export specify columns
  #def self.to_csv(column_names, handies,options = {})
  # column_names =[ "item"  , "pccitem", "receivedate" ,"startdate" ,"finishdate" , "solution"]
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |handy|
        csv << handy.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/handies_controller.rb
class HandiesController < ApplicationController
  before_action :set_handy, only: [:show, :edit, :update, :destroy ]
  before_action :authenticate_user! , only: [:new, :create, :edit, :update, :destroy]
  # GET /handies
  # GET /handies.json
  def index
    if params[:search]
         @handies = Handy.where('pccitem LIKE ? OR receivedate LIKE ? OR startdate LIKE ? OR
          finishdate LIKE ? OR schedule LIKE ? OR qual LIKE ? OR solution LIKE ? OR capacity LIKE ?',
           "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%",
           "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
      else
      @handies = Handy.all
      respond_to do |format|
            format.html 
            format.json 
            format.csv { send_data @handies.to_csv }
            format.xls { send_data @handies.to_csv } 
                end  

      #@handies = Handy.paginate(page:params[:page], per_page: 30 )
        
       end 
  end




  # GET /handies/1    
  # GET /handies/1.json

  def show 
    respond_to do |format|
            format.html 
            format.json 
            format.pdf  { render template: 'handies/report' , pdf: 'Report', layout: 'pdf.html', location: @handy } 

            end  
  end


  # GET /handies/new
  def new
    @handy = Handy.new
  end

  # GET /handies/1/edit
  def edit
  end

 
  # POST /handies
  # POST /handies.json
  def create
    @handy = Handy.new(handy_params)
    respond_to do |format|
      @handy.user = current_user
      if @handy.save
        format.html { redirect_to @handy}
        format.json { render :show, status: :created, location: @handy }
      else
        format.html { render :new }
        format.json { render json: @handy.errors, status: :unprocessable_entity }
      end
    end
  end
        

def import   
  Handy.import(params[:file])
  redirect_to handies_url, notice: "Handies imported."
end
  # PATCH/PUT /handies/1
  # PATCH/PUT /handies/1.json
  def update
    respond_to do |format|
      if @handy.update(handy_params)
        format.html { redirect_to @handy}
        format.json { render :show, status: :ok, location: @handy }
      else
        format.html { render :edit }
        format.json { render json: @handy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /handies/1
  # DELETE /handies/1.json
  def destroy
    @handy.destroy
    respond_to do |format|
      format.html { redirect_to handies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_handy
      @handy = Handy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def handy_params
      params.require(:handy).permit(:item, :pccitem, :receivedate, :startdate, :finishdate, 
        :solution, :schedule, :capacity, :qual, :read, :write, :owner, :prodname, :prodpn, :desc,
        :fwvversion, :ftype, :pcbvers, :testres , :expl, :rpname, :rpdate, :approvename, :remark,
        :pc1os, :pc1mb, :pc1vendor, :pc1chip, :pc1bios, :pc2os, :pc2mb, :pc2vendor, :pc2chip, :pc2bios,
        :pc3os, :pc3mb, :pc3vendor, :pc3chip, :pc3bios, :pc4os, :pc4mb, :pc4vendor, :pc4chip, :pc4bios,
        :pc5os, :pc5mb, :pc5vendor, :pc5chip, :pc5bios, :pc1basic, :pc1comp32, :pc1burnin,
        :pc2basic, :pc2comp32, :pc2burnin,:pc3basic, :pc3comp32, :pc3burnin, :pc4basic, :pc5basic,
        :pc1fat, :pc1fat32, :pc1ntfs, :pc1exfat, :pc1result,:pc2fat, :pc2fat32, :pc2ntfs, :pc2exfat, :pc2result,
        :pc3fat, :pc3fat32, :pc3ntfs, :pc3exfat, :pc3result, :pc4ext34, :pc4result, :pc5result,
        :pc1led, :pc2led, :pc3led, :pc4led, :pc5led, :image, :image1, :image2, :image3,
        :cdmread, :cdmwrite, :rdr112, :rdw112, :rdr4k, :rdw4k, :rdrqd324k, :rdwqd324k,
        :pc2cdmread,:pc2cdmwrite,:pc2rdr112,:pc2rdw112,:pc2rdr4k, :pc2rdw4k, :pc2rdrqd324k,:pc2rdwqd324k,
        :pc3cdmread,:pc3cdmwrite,:pc3rdr112,:pc3rdw112,:pc3rdr4k, :pc3rdw4k, :pc3rdrqd324k,:pc3rdwqd324k)
    end

  

end

app/helpers/handies_helper.rb
module HandiesHelper
end

app/views/handies/edit.html.erb
<h1>Editing Handy</h1>

<%= render 'form', handy: @handy %>

  <br><br>

<p class="imagefont" >
<font size= "20" ><%= link_to 'Show', @handy %> </font><font>| </font>
<font size= "20" ><%= link_to 'Back', handies_path %> </font>
</p>

<div style="margin-bottom: 150px;"
></div>

app/views/handies/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Handies</h1>
<%= form_tag handies_path, :method => :get do %>
  
    <%= text_field_tag :search, params[:search] , class: "search" %>
    <%= submit_tag "Search ", :name => nil  %>
<% end %>



<div class="media">
    <div class="media-body">
      <table class="table table-hover" >
  <thead>
    <tr>
      <!-- <th>Item</th>
      <th>Pccitem</th> -->
      <th>Receivedate</th>
      <th>Startdate</th>
      <th>Finishdate</th>
      <th>Solution</th>
      <th >Flash</th>
      <th>Schedule</th>
      <th>Capacity</th>
      <th>Qual</th>
      <th>Read</th>
      <th>Write</th>
      <th>Owner</th>
      <th>Result</th>      
      <th>Remark</th>
      <th id="hide">ID</th>
      <th id="hide">prodname</th>
      <th id="hide">desc</th>
      <th id="hide">prodpn</th>
      <th id="hide">fwvversion</th>
      <th id="hide">pcbvers</th>
      <th id="hide">expl</th>
      <th id="hide">rpname</th>
      <th id="hide">rpdate</th>
      <th id="hide">approvename</th>
      <th id="hide">pc1os</th>
      <th id="hide">pc1mb</th>
      <th id="hide">pc1vendor</th>
      <th id="hide">pc1chip</th>
      <th id="hide">pc1bios</th>
      <th id="hide">pc1basic</th>
      <th id="hide">pc1comp32</th>
      <th id="hide">pc1burnin</th>
      <th id="hide">pc1fat</th>
      <th id="hide">pc1fat32</th>
      <th id="hide">pc1ntfs</th>
      <th id="hide">pc1exfat</th>
      <th id="hide">pc1result</th>
      <th id="hide">pc1ntfs</th>
      <th id="hide">pc1led</th>
      <th id="hide">pc2os</th>
      <th id="hide">pc2mb</th>
      <th id="hide">pc2vendor</th>
      <th id="hide">pc2chip</th>
      <th id="hide">pc2bios</th>
      <th id="hide">pc2basic</th>
      <th id="hide">pc2comp32</th>
      <th id="hide">pc2burnin</th>
      <th id="hide">pc2fat</th>
      <th id="hide">pc2fat32</th>
      <th id="hide">pc2ntfs</th>
      <th id="hide">pc2exfat</th>
      <th id="hide">pc2result</th>
      <th id="hide">pc2led</th>
      <th id="hide">pc3os</th>
      <th id="hide">pc3mb</th>
      <th id="hide">pc3vendor</th>
      <th id="hide">pc3chip</th>
      <th id="hide">pc3bios</th>
      <th id="hide">pc3basic</th>
      <th id="hide">pc3comp32</th>
      <th id="hide">pc2burnin</th>
      <th id="hide">pc3fat</th>
      <th id="hide">pc3fat32</th>
      <th id="hide">pc3ntfs</th>
      <th id="hide">pc3exfat</th>
      <th id="hide">pc3result</th>
      <th id="hide">pc3led</th>
      <th id="hide">pc4os</th>
      <th id="hide">pc4mb</th>
      <th id="hide">pc4vendor</th>
      <th id="hide">pc4chip</th>
      <th id="hide">pc4bios</th>
      <th id="hide">pc4basic</th>
      <th id="hide">pc4ext34</th>
      <th id="hide">pc4result</th>
      <th id="hide">pc4led</th>
      <th id="hide">pc5os</th>
      <th id="hide">pc5mb</th>
      <th id="hide">pc5vendor</th>
      <th id="hide">pc5chip</th>
      <th id="hide">pc5bios</th>
      <th id="hide">pc5basic</th>
      <th id="hide">pc5result</th>
      <th id="hide">pc5led</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="sortable" >
    <% @handies.each do |handy| %>
      <tr>
        <!-- <td><%= handy.item %></td>
        <td><%= handy.pccitem %></td> -->
        <td><%= handy.receivedate  %></td>
        <td><%= handy.startdate %></td>
        <td><%= handy.finishdate %></td>
        <td><%= handy.solution %></td>
        <th ><%= handy.ftype %></th>
        <td><%= handy.schedule %></td>
        <td><%= handy.capacity %></td>
        <td><%= handy.qual %></td>
        <td><%= handy.read %></td>
        <td><%= handy.write %></td>
        <td><%= handy.owner %></td>
        <th><%= handy.testres %></th>
        <td><%= handy.remark %></td>
        <td id="hide"><%=  handy.id %></td>
       <th id="hide"><%= handy.prodname %></th>
      <th id="hide"><%= handy.desc %></th>
      <th id="hide"><%= handy.prodpn %></th>
      <th id="hide"><%= handy.fwvversion %></th>
      <th id="hide"><%= handy.pcbvers %></th>
      <th id="hide"><%= handy.expl %></th>
      <th id="hide"><%= handy.rpname %></th>
      <th id="hide"><%= handy.rpdate %></th>
      <th id="hide"><%= handy.approvename %></th>
      <th id="hide"><%= handy.pc1os %></th>
      <th id="hide"><%= handy.pc1mb %></th>
      <th id="hide"><%= handy.pc1vendor %></th>
      <th id="hide"><%= handy.pc1chip %></th>
      <th id="hide"><%= handy.pc1bios %></th>
      <th id="hide"><%= handy.pc1basic %></th>
      <th id="hide"><%= handy.pc1comp32 %></th>
      <th id="hide"><%= handy.pc1burnin %></th>
      <th id="hide"><%= handy.pc1fat %></th>
      <th id="hide"><%= handy.pc1fat32 %></th>
      <th id="hide"><%= handy.pc1ntfs %></th>
      <th id="hide"><%= handy.pc1exfat %></th>
      <th id="hide"><%= handy.pc1result %></th>
      <th id="hide"><%= handy.pc1led %></th>
       <th id="hide"><%= handy.pc2os %></th>
      <th id="hide"><%= handy.pc2mb %></th>
      <th id="hide"><%= handy.pc2vendor %></th>
      <th id="hide"><%= handy.pc2chip %></th>
      <th id="hide"><%= handy.pc2bios %></th>
      <th id="hide"><%= handy.pc2basic %></th>
      <th id="hide"><%= handy.pc2comp32 %></th>
      <th id="hide"><%= handy.pc2burnin %></th>
      <th id="hide"><%= handy.pc2fat %></th>
      <th id="hide"><%= handy.pc2fat32 %></th>
      <th id="hide"><%= handy.pc2ntfs %></th>
      <th id="hide"><%= handy.pc2exfat %></th>
      <th id="hide"><%= handy.pc2result %></th>
      <th id="hide"><%= handy.pc2led %></th>
      <th id="hide"><%= handy.pc3os %></th>
      <th id="hide"><%= handy.pc3mb %></th>
      <th id="hide"><%= handy.pc3vendor %></th>
      <th id="hide"><%= handy.pc3chip %></th>
      <th id="hide"><%= handy.pc3bios %></th>
      <th id="hide"><%= handy.pc3basic %></th>
      <th id="hide"><%= handy.pc3comp32 %></th>
      <th id="hide"><%= handy.pc3burnin %></th>
      <th id="hide"><%= handy.pc3fat %></th>
      <th id="hide"><%= handy.pc3fat32 %></th>
      <th id="hide"><%= handy.pc3ntfs %></th>
      <th id="hide"><%= handy.pc3exfat %></th>
      <th id="hide"><%= handy.pc3result %></th>
      <th id="hide"><%= handy.pc3led %></th>
      <th id="hide"><%= handy.pc4os %></th>
      <th id="hide"><%= handy.pc4mb %></th>
      <th id="hide"><%= handy.pc4vendor %></th>
      <th id="hide"><%= handy.pc4chip %></th>
      <th id="hide"><%= handy.pc4bios %></th>
      <th id="hide"><%= handy.pc4basic %></th>
      <th id="hide"><%= handy.pc4ext34 %></th>
      <th id="hide"><%= handy.pc4result %></th>
      <th id="hide"><%= handy.pc4led %></th>
      <th id="hide"><%= handy.pc5os %></th>
      <th id="hide"><%= handy.pc5mb %></th>
      <th id="hide"><%= handy.pc5vendor %></th>
      <th id="hide"><%= handy.pc5chip %></th>
      <th id="hide"><%= handy.pc5bios %></th>
      <th id="hide"><%= handy.pc5basic %></th>
      <th id="hide"><%= handy.pc5result %></th>
      <th id="hide"><%= handy.pc5led %></th>

     
      <!-- -->
      <% if current_user  %>
        <td><%= link_to 'Show', handy , class: 'btn btn-mini btn-default' , :style => 'text-decoration:none;'%></td>
        <td><%= link_to 'Edit', edit_handy_path(handy) , class: 'btn btn-mini btn-primary' , :style => 'text-decoration:none;' %></td>
        <td><%= link_to 'Destroy', handy, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-mini btn-danger' , :style => 'text-decoration:none;'%></td>
      </tr>
    <% end %>
        <% end %>
  </tbody>
</table>
</div>
</div>

<br>


<%= link_to 'Create new item', new_handy_path , class: 'btn btn-default' , :style => 'text-decoration:none;'%> 


<h3>Import CSV file</h3>
<%= form_tag  import_handies_path , multipart: true do %>
<%= file_field_tag :file %>
<%= submit_tag "Upload CSV file"  , class: 'btn btn-default'%>
<% end %>



<h3>Export file </h3>
<%= link_to 'Download CSV', handies_path(format: "csv") , class: 'btn btn-default' , :style => 'text-decoration:none;'%> |
<%= link_to "Download Excel", handies_path(format: "xls") , class: 'btn btn-default' , :style => 'text-decoration:none;'%>


<br><br>

<div style="margin-bottom: 150px;">
  
</div>

app/views/handies/new.html.erb
<h1>New Handy</h1>

<%= render 'form', handy: @handy %>

<p class="imagefont">

<font size= "20" ><%= link_to 'Back', handies_path %></font>
</p>

<div style="margin-bottom: 150px;"
></div>

app/views/handies/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= link_to 'Download PDF' , handy_url(format: "pdf"), class: 'btn btn-primary'%>
</h1>
<h1>Product Description </h1>

<table style="width:50%;">
  <tr>
  <td id="desc" >Product Name:</td>
  <td id="descline" ><%= @handy.prodname %></td>
  </tr>
  <tr>
    <td id="desc" >Product P/N:</td>
    <td id="descline" ><%= @handy.prodpn %></td>
  </tr>
   <tr>
    <td id="desc" >Firmware Version:</td>
    <td id="descline"><%= @handy.fwvversion %></td>
  </tr>
   <tr>
    <td id="desc" > Description:</td>
    <td id="descline"><%= @handy.desc %></td>
  </tr>
   <tr>
    <td id="desc" > Controller:</td>
    <td id="descline"><%= @handy.solution %></td>
  </tr>
   <tr>
    <td id="desc" >Flash Type:</td>
    <td id="descline"><%= @handy.ftype %></td>
  </tr>
   <tr>
    <td id="desc" >PCB Version:</td>
    <td id="descline"><%= @handy.pcbvers %></td>
  </tr>
   <tr>
    <td id="desc" >Qualification:</td>
    <td id="descline"><%= @handy.qual %></td>
  </tr>
   <tr>
    <td id="desc">Test Result:</td>
    <td id="descline"><%= @handy.testres %></td>
  </tr>
   <tr>
    <td id="desc" >Explain:</td>
    <td id="descline"><%= @handy.prodname %> <%= @handy.capacity %> <%= @handy.qual %> <%= @handy.solution %> <%=@handy.ftype %></td>
  </tr>
  </table>


<h1>Product Description </h1>

<div class="media">
    <div class="media-body">
      <table class="table table-hover">
  <thead>
    <tr>
      <th id="indexbarcolor">Item</th>
      <th id="indexbarcolor">Pccitem</th>
      <th id="indexbarcolor">Receivedate</th>
      <th id="indexbarcolor">Startdate</th>
      <th id="indexbarcolor">Finishdate</th>
      <th id="indexbarcolor">Solution</th>
      <th id="indexbarcolor">Schedule</th>
      <th id="indexbarcolor">Capacity</th>
      <th id="indexbarcolor">Qual</th>
      <th id="indexbarcolor">Read</th>
      <th id="indexbarcolor">Write</th>
      <th id="indexbarcolor">Owner</th>
      <th id="indexbarcolor">Remark</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @handy.item %></td>
        <td><%= @handy.pccitem %></td>
        <td><%= @handy.receivedate  %></td>
        <td><%= @handy.startdate %></td>
        <td><%= @handy.finishdate %></td>
        <td><%= @handy.solution %></td>
        <td><%= @handy.schedule %></td>
        <td><%= @handy.capacity %></td>
        <td><%= @handy.qual %></td>
        <td><%= @handy.read %></td>
        <td><%= @handy.write %></td>
        <td><%= @handy.owner %></td>
        <td><%= @handy.remark %></td>
</tr>
</tbody>
</table>

<br>

<h1>M/B Description </h1>
<div class="media">
    <div class="media-body">
      <table class="table table-hover">
  <thead>
    <tr>
      <th id="indexbarcolor">PC</th>
      <th id="indexbarcolor">OS</th>
      <th id="indexbarcolor">M/B</th>
      <th id="indexbarcolor">Vendor</th>
      <th id="indexbarcolor">Chip</th>
      <th id="indexbarcolor">BIOS</th>
      <th id="indexbarcolor">Basic Test</th>
      <th id="indexbarcolor">LED</th>
      <th id="indexbarcolor">Comp32</th>
      <th id="indexbarcolor">Burnin</th>
      <th id="indexbarcolor">FAT</th>
      <th id="indexbarcolor">FAT32</th>
      <th id="indexbarcolor">NTFS</th>
      <th id="indexbarcolor">exFAT</th>
      <th id="indexbarcolor">Result</th>
      <th  id="indexbarcolor" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>1</th>
        <td><%= @handy.pc1os %></td>
        <td><%= @handy.pc1mb %></td>
        <td><%= @handy.pc1vendor  %></td>
        <td><%= @handy.pc1chip %></td>
        <td><%= @handy.pc1bios %></td>
        <td><%= @handy.pc1basic %></td>
        <td><%= @handy.pc1led %></td>
        <td><%= @handy.pc1comp32 %></td>
        <td><%= @handy.pc1burnin %></td>
        <td><%= @handy.pc1fat %></td>
        <td><%= @handy.pc1fat32 %></td>
        <td><%= @handy.pc1ntfs %></td>
        <td><%= @handy.pc1exfat %></td>
        <td><%= @handy.pc1result %></td>
</tr>
</tbody>
  <tbody>
      <tr>
        <td>2</th>
        <td><%= @handy.pc2os %></td>
        <td><%= @handy.pc2mb %></td>
        <td><%= @handy.pc2vendor  %></td>
        <td><%= @handy.pc2chip %></td>
        <td><%= @handy.pc2bios %></td>
        <td><%= @handy.pc2basic %></td>
        <td><%= @handy.pc2led %></td>
        <td><%= @handy.pc2comp32 %></td>
        <td><%= @handy.pc2burnin %></td>
        <td><%= @handy.pc2fat %></td>
        <td><%= @handy.pc2fat32 %></td>
        <td><%= @handy.pc2ntfs %></td>
        <td><%= @handy.pc2exfat %></td>
        <td><%= @handy.pc2result %></td>
</tr>
</tbody>
  <tbody>
      <tr>
        <td>3</th>
        <td><%= @handy.pc3os %></td>
        <td><%= @handy.pc3mb %></td>
        <td><%= @handy.pc3vendor  %></td>
        <td><%= @handy.pc3chip %></td>
        <td><%= @handy.pc3bios %></td>
        <td><%= @handy.pc3basic %></td>
        <td><%= @handy.pc3led %></td>
        <td><%= @handy.pc3comp32 %></td>
        <td><%= @handy.pc3burnin %></td>
        <td><%= @handy.pc3fat %></td>
        <td><%= @handy.pc3fat32 %></td>
        <td><%= @handy.pc3ntfs %></td>
        <td><%= @handy.pc3exfat %></td>
        <td><%= @handy.pc3result %></td>
</tr>
</tbody>


<tbody>
      <tr>
        <td>4</th>
        <td><%= @handy.pc4os %></td>
        <td><%= @handy.pc4mb %></td>
        <td><%= @handy.pc4vendor  %></td>
        <td><%= @handy.pc4chip %></td>
        <td><%= @handy.pc4bios %></td>
        <td><%= @handy.pc4basic %></td>
        <td><%= @handy.pc4led %></td>
        <td></td>
        <td></td>
        <td><%= @handy.pc4ext34  %>(ext3,4)</td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= @handy.pc4result %></td>
</tr>
</tbody>

<tbody>
      <tr>
        <td>5</th>
        <td><%= @handy.pc5os %></td>
        <td><%= @handy.pc5mb %></td>
        <td><%= @handy.pc5vendor  %></td>
        <td><%= @handy.pc5chip %></td>
        <td><%= @handy.pc5bios %></td>
        <td><%= @handy.pc5basic %></td>
        <td><%= @handy.pc5led %></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td><%= @handy.pc5result %></td>
</tr>
</tbody>
</table>



<h1>CrystalDiskMark </h1>
<div class="media">
    <div class="media-body">
      <table class="table table-hover">
  <thead>
    <tr>
    <th id="indexbarcolor">PC</th>
      <th id="indexbarcolor">Read</th>
      <th id="indexbarcolor">Write</th>
      <th id="indexbarcolor">Random read 512K</th>
      <th id="indexbarcolor">andom write 512K</th>
      <th id="indexbarcolor">Random read 4K</th>
      <th id="indexbarcolor">Random write 4K</th>
      <th id="indexbarcolor">Random read QD32 4K</th>
      <th id="indexbarcolor">Random write QD32 4K</th>
      <th  id="indexbarcolor" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>1</th>
        <td><%= @handy.cdmread %></td>
        <td><%= @handy.cdmwrite %></td>
        <td><%= @handy.rdr112  %></td>
        <td><%= @handy.rdw112 %></td>
        <td><%= @handy.rdr4k %></td>
        <td><%= @handy.rdw4k %></td>
        <td><%= @handy.rdrqd324k %></td>
        <td><%= @handy.rdwqd324k %></td>
        <t
</tr>
</tbody>
  <tbody>
      <tr>
        <td>2</th>
        <td><%= @handy.pc2cdmread %></td>
        <td><%= @handy.pc2cdmwrite %></td>
        <td><%= @handy.pc2rdr112  %></td>
        <td><%= @handy.pc2rdw112 %></td>
        <td><%= @handy.pc2rdr4k %></td>
        <td><%= @handy.pc2rdw4k %></td>
        <td><%= @handy.pc2rdrqd324k %></td>
        <td><%= @handy.pc2rdwqd324k %></td>
       
</tr>
</tbody>
  <tbody>
      <tr>
        <td>3</th>
        <td><%= @handy.pc3cdmread %></td>
        <td><%= @handy.pc3cdmwrite %></td>
        <td><%= @handy.pc3rdr112  %></td>
        <td><%= @handy.pc3rdw112 %></td>
        <td><%= @handy.pc3rdr4k %></td>
        <td><%= @handy.pc3rdw4k %></td>
        <td><%= @handy.pc3rdrqd324k %></td>
        <td><%= @handy.pc3rdwqd324k %></td>
        
</tr>
</tbody>
</table>



<table> 
<h1>Benchmark</h1>
<td><%= link_to image_tag(@handy.image.url(:thumb)), @handy.image.url %></td>


<td><%= link_to image_tag(@handy.image1.url(:thumb)), @handy.image1.url %></td>

<td><%= link_to image_tag(@handy.image2.url(:thumb)), @handy.image2.url %></td>

<td><%= link_to image_tag(@handy.image3.url(:thumb)), @handy.image3.url %></td>
</table>

<font size= "20" ><%= link_to 'Edit', edit_handy_path(@handy) %></font> <font size= "20" >|</font>
<font size= "20" ><%= link_to 'Back', handies_path %></font>


<div style="margin-bottom: 150px;">
  
</div>