config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :contacts  
  resources :posts 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/home'

  resources :handies
  resources :eflashssds
  devise_for :users

resources :handies do
  	collection { post :import , :report}
end

resources :eflashssds do
    collection { post :import }
end

  root to: 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/eflashssd.rb
class Eflashssd < ApplicationRecord
belongs_to :user , optional: true

has_attached_file  :image1,
  styles: 
  {   large: "500x500", 
      medium: "346x346",
      thumb: "200x200"}, 
      default_url: ""# "/images/:style/missing.png"

      has_attached_file :image2,
  styles: 
  {   large: "500x500", 
      medium: "346x346",
      thumb: "200x200"}, 
      default_url: ""# "/images/:style/missing.png"

      has_attached_file :image3, 
  styles: 
  {   large: "500x500", 
      medium: "600x600",
      thumb: "200x200"}, 
      default_url: ""# "/images/:style/missing.png"

  #This validates the type of file uploaded. According to this, only images are allowed.
  # validates_attachment_content_type :image, :image1, :image2, :image3,   content_type: /\Aimage\/.*\z/

  #Use this if you do not want to validate the uploaded file type.
     do_not_validate_attachment_file_type :image1

 #Validates file, file type and file size
   validates_attachment  :image1, :image2, :image3,  
   content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] },
   size: { in: 0..10000.kilobytes }


	def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Eflashssd.create! row.to_hash
    end
  end

def self.to_csv(options = {})
  # if export specify columns
  #def self.to_csv(column_names, handies,options = {})
  # column_names =[ "item"  , "pccitem", "receivedate" ,"startdate" ,"finishdate" , "solution"]
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |eflashssd|
        csv << eflashssd.attributes.values_at(*column_names)
      end
    end
  end
end

app/controllers/eflashssds_controller.rb
class EflashssdsController < ApplicationController
	before_action :set_eflashssd, only: [:show, :edit, :update, :destroy ]

  def index
     if params[:search]
         @eflashssds = Eflashssd.where('pccitem LIKE ? OR receivedate LIKE ? OR startdate LIKE ? OR
          finishdate LIKE ? OR qual LIKE ? OR solution LIKE ? OR capacity LIKE ?',
           "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", 
           "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
      else

  	@eflashssds = Eflashssd.all
    respond_to do |format|
            format.html 
            format.json 
            format.csv { send_data @eflashssds.to_csv }
            format.xls { send_data @eflashssds.to_csv } 
                end  

      #@eflashssds = Eflashssd.paginate(page:params[:page], per_page: 30 )
        
       end 
  end



  def new
  	@eflashssd = Eflashssd.new
  end

  def show
  	respond_to do |format|
            format.html 
            format.json 
            format.pdf  { render template: 'eflashssds/report' , pdf: 'Report', layout: 'pdf.html', location: @handy } 
            end 
  end


  def edit
  end

def create
    @eflashssd = Eflashssd.new(eflashssd_params)
      @eflashssd.user = current_user
      if @eflashssd.save
        redirect_to @eflashssd
      else
        render 'new'    
      end
  end

def update
      if @eflashssd.update(eflashssd_params)
        render 'show' 
      else
        render 'edit'
      end
    
  end

  
  def destroy
    @eflashssd.destroy
       redirect_to eflashssds_url 
      
   end

def import   
  Eflashssd.import(params[:file])
  redirect_to eflashssds_url, notice: "Eflashssds imported."
end

private 
  	def set_eflashssd
      @eflashssd = Eflashssd.find(params[:id])
    end

	

def eflashssd_params
	params.require(:eflashssd).permit(:pccitem, :receivedate, :startdate, :finishdate,:solution, :capacity, 
		:qual, :owner, :prodname, :prodpn, :desc, :fwvversion, :ftype, :pcbvers, :testres , :expl, :rpname, 
		:rpdate, :approvename, :remark, :pc1os  ,:pc1mb  ,:pc1vendor ,:pc1chip  ,:pc1bios  ,:pc1interface ,
        :pc1basic  ,:pc1comp32  ,:pc1burnin  ,:pc1wboot  ,:pc1cboot  ,:pc1fat  ,:pc1fat32  ,:pc1ntfs ,
        :pc1exfat  ,:pc1result  ,:pc1led  ,:pc1inos1  ,:pc1inos2  , :pc1inos3 , :pc1inos4  ,:pc1inos5, 
        :pc2os ,:pc2mb ,:pc2vendor ,:pc2chip ,:pc2bios ,:pc2interface ,:pc2basic ,:pc2result ,:pc2led ,
        :pc2inos1  ,:pc2inos2  ,:pc2inos3  ,:pc2inos4  ,:pc2inos5  ,:pc2inos6  ,:pc2inos7  ,:pc2inos8 ,
        :pc3os  ,:pc3mb  ,:pc3vendor  ,:pc3chip  ,:pc3bios  ,:pc3interface,
		:pc4os  ,:pc4mb  ,:pc4vendor  ,:pc4chip  ,:pc4bios  ,:pc4interface,
		:image1, :image2, :image3, :qty, :coldbootfail, :qtreport , :plandate, :status)
end


end

app/helpers/eflashssds_helper.rb
module EflashssdsHelper
end

app/views/eflashssds/edit.html.erb
<h1>Editing E-flash-SSD</h1>

<%= render 'form', eflashssd: @eflashssd %>

<br><br>

<p class="imagefont" >
<font size= "20" ><%= link_to 'Show', @eflashssd %> </font><font>| </font>
<font size= "20" ><%= link_to 'Back', eflashssds_path %> </font>
</p>

<div style="margin-bottom: 150px;">
  
</div>

app/views/eflashssds/index.html.erb
  <p id="notice"><%= notice %></p>


<h1>E-Flash-SSD</h1>
<%= form_tag eflashssds_path, :method => :get do %>
  
    <%= text_field_tag :search, params[:search] , class: "search" %>
    <%= submit_tag "Search ", :name => nil  %>
<% end %>



<div class="media">
    <div class="media-body">
      <table class="table table-hover" >
  <thead>
    <tr>
      <th id="hide">ID</th>
      <th>Pccitem</th>
      <th>Receivedate</th>
      <th id="hide">prodpn</th>
      <th>Solution</th>
      <th>Flash</th>
      <th id="hide">desc</th>
      <th>Capacity</th>
      <th id="hide">fwvversion</th>
      <th>Qual</th>
      <th>Q'ty</th>
      <th id="hide">Plan date</th>
      <th>Startdate</th>
      <th>Finishdate</th>
      <th>Result</th>
      <th id="hide">Status</th>
      <th id="hide">Cold Boot & Power Failure</th>
      <th>Owner</th>
      <th id="hide">Qual Report</th>  
      <th>Remark</th>
      <th id="hide">expl</th>

      <th id="hide">prodname</th>
      <th id="hide">pcbvers</th>
      <th id="hide">rpname</th>
      <th id="hide">rpdate</th>
      <th id="hide">approvename</th>
      <th id="hide">pc1os</th>
      <th id="hide">pc1mb</th>
      <th id="hide">pc1vendor</th>
      <th id="hide">pc1chip</th>
      <th id="hide">pc1bios</th>
      <th id="hide">pc1interface</th>
      <th id="hide">pc1basic</th>
      <th id="hide">pc1comp32</th>
      <th id="hide">pc1burnin</th> 
      <th id="hide">pc1wboot</th> 
      <th id="hide">pc1cboot</th> 
      <th id="hide">pc1fat</th>
      <th id="hide">pc1fat32</th>
      <th id="hide">pc1ntfs</th>
      <th id="hide">pc1exfat</th>
      <th id="hide">pc1result</th>
      <th id="hide">pc1led</th>
      <th id="hide">pc1inos1</th>
      <th id="hide">pc1inos2</th>
      <th id="hide">pc1inos3</th>
      <th id="hide">pc1inos4</th>
      <th id="hide">pc1inos5</th>
      <th id="hide">pc2os</th>
      <th id="hide">pc2mb</th>
      <th id="hide">pc2vendor</th>
      <th id="hide">pc2chip</th>
      <th id="hide">pc2bios</th>      
      <th id="hide">pc2interface</th>
      <th id="hide">pc2basic</th>
      <th id="hide">pc2result</th>
      <th id="hide">pc2led</th>
      <th id="hide">pc2inos1</th>
      <th id="hide">pc2inos2</th>
      <th id="hide">pc2inos3</th>
      <th id="hide">pc2inos4</th>
      <th id="hide">pc2inos5</th>
      <th id="hide">pc2inos6</th>
      <th id="hide">pc2inos7</th>
      <th id="hide">pc2inos8</th>
      <th id="hide">pc3os</th>
      <th id="hide">pc3mb</th>
      <th id="hide">pc3vendor</th>
      <th id="hide">pc3chip</th>
      <th id="hide">pc3bios</th>
      <th id="hide">pc3interface</th>
      <th id="hide">pc4os</th>
      <th id="hide">pc4mb</th>
      <th id="hide">pc4vendor</th>
      <th id="hide">pc4chip</th>
      <th id="hide">pc4bios</th>
      <th id="hide">pc4interface</th>
      
     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="sortable" >
    <% @eflashssds.each do |eflashssd| %>
      <tr>
        <td id="hide"><%= eflashssd.id %></td>
        <td><%= eflashssd.pccitem %></td>
        <td><%= eflashssd.receivedate  %></td>
        <th id="hide"><%= eflashssd.prodpn %></th>
        <td><%= eflashssd.solution %></td>
        <th><%= eflashssd.ftype %></th>
        <th id="hide"><%= eflashssd.desc %></th>
        <td><%= eflashssd.capacity %></td>
        <th id="hide"><%= eflashssd.fwvversion %></th>
        <td><%= eflashssd.qual %></td>
        <td ><%= eflashssd.qty %></td>
        <td id="hide"><%= eflashssd.plandate %></td>
        <td><%= eflashssd.startdate %></td>
        <td><%= eflashssd.finishdate %></td>
        <th><%= eflashssd.testres %></th>
        <th id="hide"><%= eflashssd.status %></th>
        <th id="hide"><%= eflashssd.coldbootfail %></th>        
        <td><%= eflashssd.owner %></td>
        <td id="hide"><%= eflashssd.qtreport %></td>
        <td><%= eflashssd.remark %></td>
      <th id="hide"><%= eflashssd.expl %></th> 

      <th id="hide"><%= eflashssd.prodname %></th>
      <th id="hide"><%= eflashssd.pcbvers %></th>
      <th id="hide"><%= eflashssd.rpname %></th>
      <th id="hide"><%= eflashssd.rpdate %></th>
      <th id="hide"><%= eflashssd.approvename %></th>
      <th id="hide"><%= eflashssd.pc1os %></th>
      <th id="hide"><%= eflashssd.pc1mb %></th>
      <th id="hide"><%= eflashssd.pc1vendor %></th>
      <th id="hide"><%= eflashssd.pc1chip %></th>
      <th id="hide"><%= eflashssd.pc1bios %></th>
      <th id="hide"><%= eflashssd.pc1interface %></th>
      <th id="hide"><%= eflashssd.pc1basic %></th>
      <th id="hide"><%= eflashssd.pc1comp32 %></th>
      <th id="hide"><%= eflashssd.pc1burnin %></th>
      <th id="hide"><%= eflashssd.pc1wboot %></th>
      <th id="hide"><%= eflashssd.pc1cboot %></th>
      <th id="hide"><%= eflashssd.pc1fat %></th>
      <th id="hide"><%= eflashssd.pc1fat32 %></th>
      <th id="hide"><%= eflashssd.pc1ntfs %></th>
      <th id="hide"><%= eflashssd.pc1exfat %></th>
      <th id="hide"><%= eflashssd.pc1result %></th>
      <th id="hide"><%= eflashssd.pc1led %></th>
      <th id="hide"><%= eflashssd.pc1inos1 %></th>
      <th id="hide"><%= eflashssd.pc1inos2 %></th>
      <th id="hide"><%= eflashssd.pc1inos3 %></th>
      <th id="hide"><%= eflashssd.pc1inos4 %></th>
      <th id="hide"><%= eflashssd.pc1inos5 %></th>
      <th id="hide"><%= eflashssd.pc2os %></th>
      <th id="hide"><%= eflashssd.pc2mb %></th>
      <th id="hide"><%= eflashssd.pc2vendor %></th>
      <th id="hide"><%= eflashssd.pc2chip %></th>
      <th id="hide"><%= eflashssd.pc2bios %></th>
      <th id="hide"><%= eflashssd.pc2interface %></th>
	    <th id="hide"><%= eflashssd.pc2basic %></th>
      <th id="hide"><%= eflashssd.pc2result %></th>
      <th id="hide"><%= eflashssd.pc2led %></th>
      <th id="hide"><%= eflashssd.pc2inos1 %></th>
      <th id="hide"><%= eflashssd.pc2inos2 %></th>
      <th id="hide"><%= eflashssd.pc2inos3 %></th>
      <th id="hide"><%= eflashssd.pc2inos4 %></th>
      <th id="hide"><%= eflashssd.pc2inos5 %></th>
      <th id="hide"><%= eflashssd.pc2inos6 %></th>
      <th id="hide"><%= eflashssd.pc2inos7 %></th>
      <th id="hide"><%= eflashssd.pc2inos8 %></th>
      <th id="hide"><%= eflashssd.pc3os %></th>
      <th id="hide"><%= eflashssd.pc3mb %></th>
      <th id="hide"><%= eflashssd.pc3vendor %></th>
      <th id="hide"><%= eflashssd.pc3chip %></th>
      <th id="hide"><%= eflashssd.pc3bios %></th>
      <th id="hide"><%= eflashssd.pc3interface %></th>
      <th id="hide"><%= eflashssd.pc4os %></th>
      <th id="hide"><%= eflashssd.pc4mb %></th>
      <th id="hide"><%= eflashssd.pc4vendor %></th>
      <th id="hide"><%= eflashssd.pc4chip %></th>
      <th id="hide"><%= eflashssd.pc4bios %></th>
      <th id="hide"><%= eflashssd.pc4interface %></th>
    
     
      <!-- -->
      <% if current_user  %>
        <td><%= link_to 'Show', eflashssd , class: 'btn btn-mini btn-default'  , :style => 'text-decoration:none;'%></td>
        <td><%= link_to 'Edit', edit_eflashssd_path(eflashssd) , class: 'btn btn-mini btn-primary'  , :style => 'text-decoration:none;'%></td>
        <td><%= link_to 'Destroy', eflashssd, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-mini btn-danger' , :style => 'text-decoration:none;'%></td>
      </tr>
    <% end %>
        <% end %>
  </tbody>
</table>
</div>
</div>

<br>


<%= link_to 'Create new item', new_eflashssd_path , class: 'btn btn-default' , :style => 'text-decoration:none;'%> 


<h3>Import CSV file</h3>
<%= form_tag  import_eflashssds_path , multipart: true do %>
<%= file_field_tag :file %>
<%= submit_tag "Upload CSV file"  , class: 'btn btn-default'%>
<% end %>



<h3>Export file </h3>
<%= link_to 'Download CSV', eflashssds_path(format: "csv") , class: 'btn btn-default' , :style => 'text-decoration:none;'%> |
<%= link_to "Download Excel", eflashssds_path(format: "xls") , class: 'btn btn-default' , :style => 'text-decoration:none;'%>


<br><br>

<div style="margin-bottom: 150px;">
  
</div>

app/views/eflashssds/new.html.erb
<h1>New E-flash-SSD</h1>

<%= render 'form', eflashssd: @eflashssd %>

<br><br>

<p class="imagefont">
<font size= "20" ><%= link_to 'Back', eflashssds_path %></font>
</p>

<div style="margin-bottom: 150px;">
  
</div>

app/views/eflashssds/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= link_to 'Download PDF' , eflashssd_url(format: "pdf"), class: 'btn btn-primary'%>
</h1>
<h1>Product Description </h1>

<table style="width:50%;">
  <tr >
  <td id="desc" >Product Name:</td>
  <td id="descline" ><%= @eflashssd.prodname %></td>
  </tr>
  <tr>
    <td id="desc" >Product P/N:</td>
    <td id="descline" ><%= @eflashssd.prodpn %></td>
  </tr>
   <tr>
    <td id="desc" >Firmware Version:</td>
    <td id="descline"><%= @eflashssd.fwvversion %></td>
  </tr>
   <tr>
    <td id="desc" > Description:</td>
    <td id="descline"><%= @eflashssd.desc %></td>
  </tr>
   <tr>
    <td id="desc" > Controller:</td>
    <td id="descline"><%= @eflashssd.solution %></td>
  </tr>
   <tr>
    <td id="desc" >Flash Type:</td>
    <td id="descline"><%= @eflashssd.ftype %></td>
  </tr>
   <tr>
    <td id="desc" >PCB Version:</td>
    <td id="descline"><%= @eflashssd.pcbvers %></td>
  </tr>
   <tr>
    <td id="desc" >Qualification:</td>
    <td id="descline"><%= @eflashssd.qual %></td>
  </tr>
   <tr>
    <td id="desc">Test Result:</td>
    <td id="descline"><%= @eflashssd.testres %></td>
  </tr>
   <tr>
    <td id="desc" >Explain:</td>
    <td id="descline"><%= @eflashssd.prodname %> <%= @eflashssd.capacity %> <%= @eflashssd.qual %> <%= @eflashssd.solution %> <%=@eflashssd.ftype %></td>
  </tr>
  </table>


<h1>Product Description </h1>

<div class="media">
    <div class="media-body">
      <table class="table table-hover">
  <thead>
    <tr>
      <th id="indexbarcolor">Pccitem</th>
      <th id="indexbarcolor">Receivedate</th>
      <th id="indexbarcolor">Plandate</th>
      <th id="indexbarcolor">Startdate</th>
      <th id="indexbarcolor">Finishdate</th>
      <th id="indexbarcolor">Solution</th>
      <th id="indexbarcolor">Capacity</th>
      <th id="indexbarcolor">Qual</th>
      <th id="indexbarcolor">Owner</th>
      <th id="indexbarcolor">Remark</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @eflashssd.pccitem %></td>
        <td><%= @eflashssd.receivedate  %></td>
        <td><%= @eflashssd.plandate  %></td>
        <td><%= @eflashssd.startdate %></td>
        <td><%= @eflashssd.finishdate %></td>
        <td><%= @eflashssd.solution %></td>
        <td><%= @eflashssd.capacity %></td>
        <td><%= @eflashssd.qual %></td>
        <td><%= @eflashssd.owner %></td>
        <td><%= @eflashssd.remark %></td>
</tr>
</tbody>
</table>

<br>

<h1>M/B Description </h1>
<div class="media">
    <div class="media-body">
      <table class="table table-hover">
  <thead>
    <tr>
      <th id="indexbarcolor">PC</th>
      <th id="indexbarcolor">OS</th>
      <th id="indexbarcolor">M/B</th>
      <th id="indexbarcolor">Vendor</th>
      <th id="indexbarcolor">Chip</th>
      <th id="indexbarcolor">BIOS</th>
      <th id="indexbarcolor">Interface</th>
      <th id="indexbarcolor">Basic Test</th>
      <th id="indexbarcolor">LED</th>
      <th id="indexbarcolor">Comp32</th>
      <th id="indexbarcolor">Burnin</th>
     <!-- <th id="indexbarcolor">FAT</th> -->
      <th id="indexbarcolor">FAT32</th>
      <th id="indexbarcolor">NTFS</th>
      <th id="indexbarcolor">Warm boot</th>
      <th id="indexbarcolor">Cold boot</th>
      <th id="indexbarcolor">OS 1</th>
      <th id="indexbarcolor">OS 2</th>
      <th id="indexbarcolor">OS 3</th>
      <th id="indexbarcolor">OS 4</th>
      <th id="indexbarcolor">OS 5</th>
      <th id="indexbarcolor">OS 6</th>
      <th id="indexbarcolor">OS 7</th>
      <th id="indexbarcolor">OS 8</th>
     <!-- <th id="indexbarcolor">exFAT</th> -->
      <th id="indexbarcolor">Result</th>
      <th  id="indexbarcolor" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td>1</th>
        <td><%= @eflashssd.pc1os %></td>
        <td><%= @eflashssd.pc1mb %></td>
        <td><%= @eflashssd.pc1vendor  %></td>
        <td><%= @eflashssd.pc1chip %></td>
        <td><%= @eflashssd.pc1bios %></td>
        <td><%= @eflashssd.pc1interface %></td>
        <td><%= @eflashssd.pc1basic %></td>
        <td><%= @eflashssd.pc1led %></td>
        <td><%= @eflashssd.pc1comp32 %></td>
        <td><%= @eflashssd.pc1burnin %></td>
        <!-- <td><%= @eflashssd.pc1fat %></td> -->
        <td><%= @eflashssd.pc1fat32 %></td>
        <td><%= @eflashssd.pc1ntfs %></td>
        <td><%= @eflashssd.pc1wboot %></td>
        <td><%= @eflashssd.pc1cboot %></td>
        <td><%= @eflashssd.pc1inos1 %></td>
        <td><%= @eflashssd.pc1inos2 %></td>
        <td><%= @eflashssd.pc1inos3 %></td>
        <td><%= @eflashssd.pc1inos4 %></td>
        <td><%= @eflashssd.pc1inos5 %></td>
        <td> </td>
        <td> </td>
        <td> </td>
        <!-- <td><%= @eflashssd.pc1exfat %></td> -->
        <td><%= @eflashssd.pc1result %></td>
</tr>
</tbody>
  <tbody>
      <tr>
        <td>2</th>
        <td><%= @eflashssd.pc2os %></td>
        <td><%= @eflashssd.pc2mb %></td>
        <td><%= @eflashssd.pc2vendor  %></td>
        <td><%= @eflashssd.pc2chip %></td>
        <td><%= @eflashssd.pc2bios %></td>
        <td><%= @eflashssd.pc2interface %></td>
        <td><%= @eflashssd.pc2basic %></td>
        <td><%= @eflashssd.pc2led %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%= @eflashssd.pc2inos1 %></td>
        <td><%= @eflashssd.pc2inos2 %></td>
        <td><%= @eflashssd.pc2inos3 %></td>
        <td><%= @eflashssd.pc2inos4 %></td>
        <td><%= @eflashssd.pc2inos5 %></td>
        <td><%= @eflashssd.pc2inos6 %></td>
        <td><%= @eflashssd.pc2inos7 %></td>
        <td><%= @eflashssd.pc2inos8 %></td>
        <td><%= @eflashssd.pc2result %></td>
</tr>
</tbody>
  <tbody>
      <tr>
        <td>3</th>
        <td><%= @eflashssd.pc3os %></td>
        <td><%= @eflashssd.pc3mb %></td>
        <td><%= @eflashssd.pc3vendor  %></td>
        <td><%= @eflashssd.pc3chip %></td>
        <td><%= @eflashssd.pc3bios %></td>
        <td><%= @eflashssd.pc3interface %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
</tr>
</tbody>


<tbody>
      <tr>
        <td>4</th>
        <td><%= @eflashssd.pc4os %></td>
        <td><%= @eflashssd.pc4mb %></td>
        <td><%= @eflashssd.pc4vendor  %></td>
        <td><%= @eflashssd.pc4chip %></td>
        <td><%= @eflashssd.pc4bios %></td>
        <td><%= @eflashssd.pc3interface %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
        <td><%=  %></td>
</tr>
</tbody>
</table>


<table> 
<h1>Crystaldiskmark</h1>

<td><%= link_to image_tag(@eflashssd.image1.url(:large)), @eflashssd.image1.url %></td>

<td><%= link_to image_tag(@eflashssd.image2.url(:large)), @eflashssd.image2.url %></td>

<td><%= link_to image_tag(@eflashssd.image3.url(:large)), @eflashssd.image3.url %></td>
</table>

<font size= "20" ><%= link_to 'Edit', edit_eflashssd_path(@eflashssd) %></font> <font size= "20" >|</font>
<font size= "20" ><%= link_to 'Back', eflashssds_path %></font>


<div style="margin-bottom: 150px;">
  
</div>