config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  resources :contacts  
  resources :posts 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/home'

  resources :handies
  resources :eflashssds
  devise_for :users

resources :handies do
  	collection { post :import , :report}
end

resources :eflashssds do
    collection { post :import }
end

  root to: 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<footer>
        <h6>garytsao-website @ 2018  </h6>
</footer>

app/views/layouts/_navbar.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top navbar-dark bg-dark" style="border-width: 0 0 0px">
        <div class="container-fluid" >
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll"  >
               
                <a class="navbar-brand" style="font-size: 35px;text-decoration:none;font-family: 'Cabin Sketch', cursive;"<%= link_to "Gary Web.  ",posts_path %></a>
            </div>


            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" >
                <ul class="nav navbar-nav navbar-right" >
                    <li><%= link_to "Blog", posts_path %></li>
                    <li><%= link_to "Contact", new_contact_path %></li>
                    <li><%= link_to "Qt works", pages_home_path %></li>
    
                <% if !user_signed_in? %>
                     <li><%= link_to "Log in User", user_session_path %></li>
                    <li><%= link_to "Sign in User", new_user_registration_path %></li>  
                    <% else %>
                    <li ><%=  link_to current_user.email %></li>
                    
                    <li><%= link_to "Log out User", destroy_user_session_path, method: :delete %></li>

                    <% end %>  
                   

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gary-website</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
   
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <link href="https://fonts.googleapis.com/css?family=Cabin+Sketch" rel="stylesheet">

<meta name="viewport" content="width=device-width, initial-scale=1"/>

   <style>
    fieldset {
      border: 0;
    }
    label {
      display: block;
      margin: 30px 0 0 0;
    }
    .overflow {
      height: 200px;
    }
  </style>

  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

  <!--
  <script>
  $( function() {
    $( "#speed" ).selectmenu();
     $( "#sortable" ).sortable();
    $( "#sortable" ).disableSelection();
    $( "#files" ).selectmenu();
 
    $( "#number" )
      .selectmenu()
      .selectmenu( "menuWidget" )
        .addClass( "overflow" );
 
    $( "#salutation" ).selectmenu();
  } );
  </script>
-->

  </head>

  <body>
  <%=  render 'layouts/navbar' %>
    <%= yield %>
<%=  render 'layouts/footer' %>
  </body>

</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
  <title></title>
        <%= wicked_pdf_stylesheet_link_tag 'pdf' %>
<style>
<link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="utf-8">

#qualreport{
    text-align: right;
    background-color: #black;
    color: #white;
}

#compatibility {
    text-align: center;
    color: blue;
}
#text-center {
    text-align: center;
}

#text-cent-col-bord {
    text-align: center;
    background-color: #cccccc;
    border:1px solid black;
}
#desc{
    font-size:x-large;
    font-weight:bold;
    padding-bottom: 10px;
    padding-left: 80px;
}

#descline{
    border-bottom-width:thin;
    border-bottom-style:solid;
    position: fixed;
    border-bottom: 2px solid;
    width: 300px;
}

#tablecolor{
    background-color: #cccccc;
}

.colord6{
    background-color: #cccccc;
}
div.static {
    position: static;
    border: 1px solid #000000;
    text-align: center;
    border-bottom: 1px;
}

#border1px {
    border:1px solid black; 
}

ol.eng {
    list-style-type: upper-alpha;
}
ol.dec {
    list-style-type: decimal;
}

#bolder{
    font-weight:bolder;
    font-size: 20px;
}
li.height{
    margin: 5px;
}

.margin5px{
    margin: 5px;
}

.newroman{
 font-family: "Times New Roman", Times, serif;
}
pre.newroman {
    font-family: "Times New Roman", Times, serif;
}

</style>
</head>
<body>
    <%= yield %>
</body>
</html>